#!/bin/bash

# Update the update-ipsets script to the newest version
curl -L https://raw.githubusercontent.com/firehol/firehol/master/sbin/update-ipsets -o /sbin/update-ipsets && chmod a+x /sbin/update-ipsets


update-ipsets -r -v
bash /bin/enable firehol_level1 
bash /bin/enable firehol_level2

while :
do
  echo "Running update-ipsets silently..."
  update-ipsets -s
  sleep 10s
done